### PR TITLE
Improvements for matching members

### PR DESCRIPTION
**Pull request by darcyparker**
Add support for 
* getters/setters
* async functions/generators
* fix some whitespace issues
* allow `$` in member names

### CODE REVIEW

**Comment by darcyparker** [comment]
There are some similar white space issues in some other lines... that I can add to this pull request or create a new one.

**Comment by darcyparker** [comment]
Similarly, `$` in other names could be added to this pull request.

**Comment by jb55** [comment]
Adding it to this one is fine

**Comment by darcyparker** [comment]
@jb55 - Okay updated.

**Comment by jb55** [comment]
thx

**Pull request merged**
